### ISSUE TITLE
tax x ba_tax

### ISSUE THREAD

**Issue by pardalismitis** [LEEClab/ms_mammals_sp_spatial_analysis#3]
Linha 149 do [00_prepara_data.R](https://github.com/pardalismitis/ms_mammals_sp_spatial_analysis/blob/main/code/00_prepara_data.R):
`dplyr::left_join(., rbind(unique(ca_occ[, c(2, 3, 4)]), tax), by = "genus") %>%` 

Seria:
`dplyr::left_join(., rbind(unique(ca_occ[, c(2, 3, 4)]), ba_tax), by = "genus") %>%`

**Comment by mauriciovancine** [comment]
Oxe, verei =]

Muito obrigado Fernando. 

Pode fazer um pull request, por favor.

**Comment by pardalismitis** [comment]
Na verdade estou assumindo. Pulei o Atlantic-Bats pois estava focando em felinos.
Vou abrir outro issue, não consegui rodar o Atlantic-Bats.
